### ISSUE TITLE
Improvement: Set default code formatting 

### ISSUE THREAD

**Issue by constant-flow** [jorgenkraghjakobsen/snapclient#41]
Hi, i think providing consistent code formatting would help to make it easier to contribute to this project.

As you already added a vscode `settings.json` and many devs these days use VSCode and it supports the `.clang-format` file, adding such a file that matches your coding style the most would be nice and helpful.

I tried to mimic the code style you use but wasn't fully able to get it right. Also some options seem to be ignored by the auto-formatter (e.g. [AllowShortEnumsOnASingleLine is ignored](https://stackoverflow.com/questions/66046969/default-working-clang-format-file-for-visual-studio))

`.clang-format`
```
Standard: Cpp11
BasedOnStyle: LLVM
IndentWidth: 4
ColumnLimit: 0
AccessModifierOffset: -4
NamespaceIndentation: All
BreakBeforeBraces: Custom
BraceWrapping:
  AfterEnum: true
  AfterStruct: true
  AfterClass: true
  SplitEmptyFunction: true
  AfterControlStatement: false
  AfterNamespace: false
  AfterFunction: false
  AfterUnion: true
  AfterExternBlock: false
  BeforeCatch: false
  BeforeElse: false
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
SpacesBeforeTrailingComments: 2
CommentPragmas: "^[^ ]"
AllowShortEnumsOnASingleLine: true
AllowShortIfStatementsOnASingleLine: true
``` 

or use the same formatting as [Snapcast (Github)](https://github.com/badaix/snapcast/blob/master/.clang-format)

Two options I like as well, u could add to `settings.json` are

```
"files.autoSave": "onFocusChange",
"editor.formatOnSave": true,
```

Anyways thanks for the great work so far. The current versions runs so smoothly on my ESP32 with a PCM5102, that i'm going to connect and test it with a ["RPI HiFi Amp HAT TAS5713"](https://www.inno-maker.com/product/hifi-amp-hat/)
